In [1]:
import numpy as np

In [3]:
a = np.arange(16)

In [5]:
a.shape

(16,)

In [18]:
d = a.reshape(4,4)

In [11]:
a.reshape(-1,1).ndim

2

In [16]:
a[:,np.newaxis, np.newaxis].ndim

3

In [17]:
np.sum(a)

120

In [22]:
np.median(d, axis=0)

array([6., 7., 8., 9.])

In [21]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
np.arange(4) + np.arange(1)

array([0, 1, 2, 3])

In [26]:
a = np.array([[1,2,3],[4,5,6]])

In [28]:
b = np.array([[11,12,13],[14,15,16],[11,22,33]])

In [29]:
a.shape

(2, 3)

In [30]:
b.shape

(3, 3)

In [31]:
a.reshape(1,2,3) + b.reshape(3,1,3)

array([[[12, 14, 16],
        [15, 17, 19]],

       [[15, 17, 19],
        [18, 20, 22]],

       [[12, 24, 36],
        [15, 27, 39]]])

In [32]:
a = np.array([[1,2],[2,3],[4,5]])

In [33]:
b = np.array([[11,2],[2,13],[4,15],[6,7],[8,8]])

In [34]:
a.shape

(3, 2)

In [35]:
b.shape

(5, 2)

In [37]:
a.reshape(3,1,2) - b.reshape(1,5,2)

array([[[-10,   0],
        [ -1, -11],
        [ -3, -13],
        [ -5,  -5],
        [ -7,  -6]],

       [[ -9,   1],
        [  0, -10],
        [ -2, -12],
        [ -4,  -4],
        [ -6,  -5]],

       [[ -7,   3],
        [  2,  -8],
        [  0, -10],
        [ -2,  -2],
        [ -4,  -3]]])